import { getInstallationOctokit } from "@/lib/github-app";
import { apiOk, apiError, parseBody, requireFields } from "@/lib/api-utils";

interface SubmitRequest {
  owner: string;
  repo: string;
  issue_number: number;
  branch_name?: string;
  title?: string;
  body?: string;
}

function computeBranchName(issueNumber: number, issueTitle: string): string {
  const slug = issueTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 40);
  return `gitmolt/issue-${issueNumber}-${slug}`;
}

export async function POST(request: Request) {
  const body = await parseBody<SubmitRequest>(request);
  if (!body) return apiError(400, "Invalid JSON");

  const err = requireFields(body, ["owner", "repo", "issue_number"]);
  if (err) return apiError(400, err);

  const { owner, repo, issue_number } = body;

  try {
    const octokit = await getInstallationOctokit(owner, repo);

    // Verify issue exists and is claimed
    const { data: issue } = await octokit.rest.issues.get({ owner, repo, issue_number });
    const labels = issue.labels.map((l: any) => (typeof l === "string" ? l : l.name ?? ""));
    if (!labels.includes("ai-claimed")) {
      return apiError(400, "Claim the issue first with claim_issue.");
    }

    // Resolve branch name
    const branchName = body.branch_name ?? computeBranchName(issue_number, issue.title);

    // Check if branch exists
    let branchExists = false;
    try {
      await octokit.rest.git.getRef({ owner, repo, ref: `heads/${branchName}` });
      branchExists = true;
    } catch {}

    if (!branchExists) {
      const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
      const { data: ref } = await octokit.rest.git.getRef({ owner, repo, ref: `heads/${repoData.default_branch}` });
      await octokit.rest.git.createRef({ owner, repo, ref: `refs/heads/${branchName}`, sha: ref.object.sha });
    }

    // Check if PR already exists
    const { data: prs } = await octokit.rest.pulls.list({ owner, repo, state: "open", head: `${owner}:${branchName}` });
    if (prs.length > 0) {
      return apiError(409, `A PR already exists (#${prs[0].number}). Use contribution_status to check it.`);
    }

    // Create Draft PR
    const prTitle = body.title ?? `🤖 Fix: ${issue.title}`;
    const prBody = body.body ?? `Closes #${issue_number}\n\n## Summary\nAI-generated contribution via GitMolt.\n\n---\n🤖 Generated by [GitMolt](https://github.com/imtemp-dev/gitmolt)`;

    const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
    const { data: pr } = await octokit.rest.pulls.create({
      owner, repo,
      title: prTitle,
      body: prBody,
      head: branchName,
      base: repoData.default_branch,
      draft: true,
    });

    // Add label + link comment
    try { await octokit.rest.issues.addLabels({ owner, repo, issue_number: pr.number, labels: ["ai-contribution"] }); } catch {}
    try { await octokit.rest.issues.createComment({ owner, repo, issue_number, body: `🤖 Draft PR created: ${pr.html_url}` }); } catch {}

    return apiOk({
      pr: { number: pr.number, url: pr.html_url, branch: branchName, isDraft: true, state: "open" },
    });
  } catch (e: any) {
    if (e.message?.includes("not installed")) return apiError(400, e.message);
    return apiError(500, e.message ?? "Failed to submit contribution");
  }
}
