import type { GitMoltClient } from "../github/client.js";
import type { ToolResponse } from "../types.js";
import { ok, err } from "../types.js";
import { classifyError } from "../github/errors.js";

function computeBranchName(issueNumber: number, issueTitle: string): string {
  const slug = issueTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 40);
  return `gitmolt/issue-${issueNumber}-${slug}`;
}

export async function handleSubmitContribution(
  args: Record<string, unknown>,
  client: GitMoltClient
): Promise<ToolResponse> {
  const owner = args.owner as string;
  const repo = args.repo as string;
  const issueNumber = args.issue_number as number;
  const branchNameArg = args.branch_name as string | undefined;
  const titleArg = args.title as string | undefined;
  const bodyArg = args.body as string | undefined;

  if (!owner || !repo || !issueNumber) {
    return err("Required: owner, repo, issue_number");
  }

  try {
    // Verify issue exists and has ai-claimed label
    const issue = await client.getIssue(owner, repo, issueNumber);
    if (!issue.labels.includes("ai-claimed")) {
      return err("Claim the issue first with claim_issue.");
    }

    // Resolve branch name
    const branchName =
      branchNameArg ?? computeBranchName(issueNumber, issue.title);

    // Check if branch exists
    const exists = await client.branchExists(owner, repo, branchName);
    if (!exists) {
      // Create branch from default branch HEAD
      await client.createBranch(owner, repo, branchName);
    }

    // Check if PR already exists for this branch
    const existingPR = await client.findPRForIssue(owner, repo, issueNumber);
    if (existingPR) {
      return err(
        `A PR already exists for this branch (#${existingPR}). Use contribution_status to check it.`
      );
    }

    // Generate PR content
    const title = titleArg ?? `🤖 Fix: ${issue.title}`;
    const body =
      bodyArg ??
      `Closes #${issueNumber}

## Summary
AI-generated contribution via GitMolt.

## Checklist
- [ ] Tests pass
- [ ] No breaking changes

---
🤖 Generated by [GitMolt](https://github.com/imtemp-dev/gitmolt)`;

    // Create Draft PR
    const pr = await client.createDraftPR({
      owner,
      repo,
      issueNumber,
      branchName,
      title,
      body,
    });

    return ok(
      `Draft PR created: ${pr.url}\n\nBranch: ${branchName}\nPR: #${pr.number}\n\nPush your code to the branch and use contribution_status to track CI/review.`
    );
  } catch (raw) {
    const error = classifyError(raw);
    if (error.kind === "auth_failure") {
      return err(
        `Cannot push to ${owner}/${repo}. Check GitMolt App installation.`
      );
    }
    return err(`Failed to submit contribution: ${error.message}`);
  }
}
